name = input("An wen geht die Nachricht? ")
absender = input("Wer ist der Absender? ")

print(f"Hallo {name}")
print("")
print("Mit dieser EMail möchte ich dich über meine neue Adresse informieren")
print("")
print("Meine neue Adresse lautet:")
print("Juri Steimann")
print("Schwarzwaldstraße 12")
print("D-78462 Konstanz")
print("Telefon: 0176 1234567")
print("Email: juri.steimann@web.de")
print("")
print(f"{absender}")